columns:
Independent_features:  

 qty_dot_url: int64 
 qty_hyphen_url: int64 
 qty_underline_url: int64 
 qty_slash_url: int64
 qty_questionmark_url: int64 
 qty_equal_url: int64 
 qty_at_url: int64 
 qty_and_url: int64
 qty_exclamation_url: int64 
 qty_space_url: int64 
 qty_tilde_url: int64 
 qty_comma_url: int64
 qty_plus_url: int64 
 qty_asterisk_url: int64 
 qty_hashtag_url: int64 
 qty_dollar_url: int64
 qty_percent_url: int64 
 qty_tld_url length_url: int64 
 qty_dot_domain: int64
 qty_hyphen_domain: int64 
 qty_underline_domain: int64 
 qty_slash_domain: int64
 qty_questionmark_domain: int64 
 qty_equal_domain: int64 
 qty_at_domain: int64
 qty_and_domain: int64 
 qty_exclamation_domain: int64 
 qty_space_domain: int64
 qty_tilde_domain: int64 
 qty_comma_domain: int64 
 qty_plus_domain: int64
 qty_asterisk_domain: int64 
 qty_hashtag_domain: int64 
 qty_dollar_domain: int64
 qty_percent_domain: int64 
 qty_vowels_domain: int64
 domain_length: int64 
 domain_in_ip: int64
 server_client_domain: int64 
 qty_dot_directory: int64 
 qty_hyphen_directory: int64
 qty_underline_directory: int64 
 qty_slash_directory: int64
 qty_questionmark_directory: int64 
 qty_equal_directory: int64 
 qty_at_directory: int64
 qty_and_directory: int64 
 qty_exclamation_directory: int64 
 qty_space_directory: int64
 qty_tilde_directory: int64 
 qty_comma_directory: int64 
 qty_plus_directory: int64
 qty_asterisk_directory: int64 
 qty_hashtag_directory: int64 
 qty_dollar_directory: int64
 qty_percent_directory: int64
 directory_length: int64 
 qty_dot_file: int64
 qty_hyphen_file: int64 
 qty_underline_file: int64 
 qty_slash_file: int64
 qty_questionmark_file: int64 
 qty_equal_file: int64 
 qty_at_file: int64 
 qty_and_file: int64
 qty_exclamation_file: int64 
 qty_space_file: int64 
 qty_tilde_file: int64 
 qty_comma_file: int64
 qty_plus_file: int64 
 qty_asterisk_file: int64 
 qty_hashtag_file: int64 
 qty_dollar_file: int64
 qty_percent_file: int64
 file_length: int64 
 qty_dot_params: int64 
 qty_hyphen_params: int64
 qty_underline_params: int64 
 qty_slash_params: int64 
 qty_questionmark_params: int64
 qty_equal_params: int64 
 qty_at_params: int64 
 qty_and_params: int64
 qty_exclamation_params: int64 
 qty_space_params: int64 
 qty_tilde_params: int64
 qty_comma_params: int64 
 qty_plus_params: int64 
 qty_asterisk_params: int64
 qty_hashtag_params: int64 
 qty_dollar_params: int64 
 qty_percent_params: int64
 params_length: int64 
 tld_present_params: int64 
 qty_params: int64
 email_in_url: int64
 time_response: float
 domain_spf: int64 
 asn_ip: int64
 time_domain_activation: int64
 time_domain_expiration: int64 
 qty_ip_resolved: int64 
 qty_nameservers: int64
 qty_mx_servers: int64 
 ttl_hostname: int64 
 tls_ssl_certificate: int64 
 qty_redirects: int64
 url_google_index: int64 
 domain_google_index: int64 
 url_shortened: int64




target_column: phishing